"""initial_schema

Revision ID: d5ea4bbb1701
Revises: 
Create Date: 2026-04-11 16:36:57.044055

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd5ea4bbb1701'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_accounts_customer_id'), 'loyalty_accounts', ['customer_id'], unique=True)
    op.create_table('point_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loyalty_account_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_history_loyalty_account_id'), 'point_history', ['loyalty_account_id'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rewards')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_point_history_loyalty_account_id'), table_name='point_history')
    op.drop_table('point_history')
    op.drop_index(op.f('ix_loyalty_accounts_customer_id'), table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    # ### end Alembic commands ###
