{
 "title": "RestoHub Performance Dashboard",
 "tags": [
  "restohub",
  "nodejs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uso de CPU - Gateway",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"restohub-gateway\"}[1m]) * 100",
     "legendFormat": "CPU Gateway"
    }
   ]
  },
  {
   "title": "Consumo de RAM - Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{job=\"restohub-gateway\"}",
     "legendFormat": "Memoria RAM Gateway"
    }
   ]
  },
  {
   "title": "Latencia Interna (Event Loop Lag)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=\"restohub-gateway\"}",
     "legendFormat": "Lag del Event Loop (Segundos)"
    }
   ]
  }
 ]
}