server {
    listen 80; # Esto es para escuchar el puerto 80

    # Sirve los archivos estáticos del frontend
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        # Esta parte de aqui es importante porque si no existiera, las rutas como
        # /ingredientes darían 404 al recargar la página
        try_files $uri $uri/ /index.html;
    }

    # Redirige las peticiones GraphQL al gateway
    # En lugar de que el frontend llame a localhost:4000, llama a /graphql
    # y Nginx lo redirige al gateway dentro de la red de Docker
    location /graphql {
        proxy_pass http://gateway:4000/graphql;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade'; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }
}