"""Add location fields

Revision ID: e0066a8ced68
Revises: f9827a1c3e44
Create Date: 2026-04-24 19:28:03.282874

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e0066a8ced68'
down_revision: Union[str, None] = 'f9827a1c3e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dishes_name', table_name='dishes')
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'address')
    op.create_index('ix_dishes_name', 'dishes', ['name'], unique=True)
    # ### end Alembic commands ###
