"""add_country_branch_orders

Revision ID: e085b2c858b8
Revises: 6d4301202cc5
Create Date: 2026-04-12 18:20:48.700030

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e085b2c858b8'
down_revision: Union[str, None] = '6d4301202cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=50), nullable=False, server_default='Colombia'))
    op.add_column('users', sa.Column('branch', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'branch')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
